---
- hosts: all-servers
  connection: local
  tasks:
    - name: add A record
      nsupdate:
        server: pri.jear.co
        key_name: 10.202.115.251.jear.co
        #key_name: rndc-key
        key_secret: ""
        zone: jear.co
        record: nfs
        value: 10.202.115.150
        #state: absent #uncomment to delete

